# Generated by Django 4.1.1 on 2022-12-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('BIRTH', models.CharField(max_length=10)),
                ('HOSPITAL', models.CharField(max_length=50)),
                ('VACCINE', models.CharField(max_length=50)),
                ('DATE', models.CharField(default='YYYY-MM-DD', max_length=10)),
                ('HOUR', models.CharField(max_length=50)),
            ],
        ),
    ]
